services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    env_file:
      - .env
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - minha_rede

  postgres:
    image: ankane/pgvector
    container_name: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - minha_rede

  evolution-api:
    container_name: lab_evolution_api
    image: atendai/evolution-api:latest
    restart: always
    ports:
      - 8080:8080
    volumes:
      - lab_evolution_instances:/lab_evolution/instances
    env_file:
      - .env
    networks:
      - minha_rede

  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    networks:
      - minha_rede

  adminer:
    image: adminer
    container_name: adminer
    restart: unless-stopped
    ports:
      - "8081:8080"
    depends_on:
      - postgres
    networks:
      - minha_rede

volumes:
  n8n_data:
  postgres_data:
  lab_evolution_instances:

networks:
  minha_rede:
    driver: bridge
